name: webblen
description: Official Webblen App
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  #ARCHITECTURE
  stacked: ^2.1.9
  stacked_services: ^0.8.8
  stacked_themes: ^0.3.5
  stacked_hooks: ^0.2.1
  flutter_hooks: ^0.17.0

  #FIRESTORE/FIREBASE
  firebase_core: ^1.3.0
  firebase_auth: ^1.4.1
  firebase_auth_oauth: ^1.0.1
  firebase_dynamic_links: ^2.0.6
  firebase_messaging: ^10.0.2
  firebase_storage: ^8.1.3
  cloud_functions: ^1.1.2
  cloud_firestore: ^2.2.1

  #ANALYTICS
  firebase_analytics: ^8.1.2

  #SOCIAL DEPENDENCIES
  google_sign_in: ^5.0.4
  flutter_facebook_auth: ^3.4.1

  #HTTP REQUESTS
  http:

  #ADD CANCELLABLE ACTIONS TO ASYNC
  async:

  #FULL TEXT SEARCH
  algolia: ^1.0.1

  #STREAM & VIDEO
  agora_rtc_engine: ^4.0.2

  #PHONE UTILITIES
  url_launcher: ^6.0.3
  share: ^2.0.1
  permission_handler: ^7.1.0
  app_settings: ^4.1.0
  shared_preferences: ^2.0.5
  wakelock: ^0.5.2
  devicelocale: ^0.4.1
  flutter_local_notifications: ^5.0.0+4
  path_provider: ^2.0.2


  #IMAGES
  transparent_image: ^2.0.0
  cached_network_image: ^3.0.0
  image_cropper: ^1.4.0
  image_picker: ^0.8.1
  flutter_image_compress: ^1.0.0
  carousel_slider: ^4.0.0-nullsafety.0
  image: ^3.0.2


  #LOCATION
  location: ^4.1.1
  geolocator: ^7.0.3
  geocode: ^1.0.1
  geoflutterfire2: ^2.3.7
  google_place: ^0.4.0
  google_maps_webservice: ^0.0.20-nullsafety.4
  google_maps_flutter: ^2.0.3
  maps_launcher: ^2.0.0

  #DATE & TIME
  flutter_calendar_carousel: ^2.0.0
  add_2_calendar: ^2.1.0

  #UI
  font_awesome_flutter: ^9.0.0
  shimmer: ^2.0.0

  #FINANCE
  flutter_credit_card: ^2.0.0
  stripe_sdk: ^5.0.0-nullsafety.0
  flutter_inapp_purchase: ^5.0.1

  #OTHER
  qr_flutter: ^4.0.0
  qr_code_scanner: ^0.4.0
  auto_size_text: ^3.0.0-nullsafety.0
  flutter_typeahead: ^3.1.1
  introduction_screen: ^2.1.0
  flutter_masked_text2: ^0.9.1
  mask_text_input_formatter: ^2.0.0-nullsafety.2
  flutter_xlider:
    git:
      url: https://github.com/mukai154/flutter_xlider.git
  intl_phone_field: ^2.0.0
  app_links: ^2.1.0
  lazy_loading_list: ^1.0.1
  video_player: ^2.1.6
  miniplayer:
    git:
      url: git://github.com/Shahmirzali-Huseynov/miniplayer_for_araf.git

dependency_overrides:
  analyzer: 

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner:
  stacked_generator: ^0.4.8


# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Helvetica Neue
      fonts:
        - asset: assets/fonts/HelveticaNeueThin.ttf
          weight: 300
        - asset: assets/fonts/HelveticaNeueLight.ttf
          weight: 400
        - asset: assets/fonts/HelveticaNeue.ttf
          weight: 500
        - asset: assets/fonts/HelveticaNeueMedium.ttf
          weight: 600
        - asset: assets/fonts/HelveticaNeueBold.ttf
          weight: 700