name: webblen
description: Official Webblen App
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  #ANALYTICS
  firebase_analytics:
  facebook_app_events:

  #SOCIAL DEPENDENCIES
  google_sign_in:
  flutter_facebook_auth:
  apple_sign_in:

  #ARCHITECTURE
  stacked:
  stacked_services:
  stacked_themes:
  get_it:
  injectable:
  observable_ish:
  auto_route:

  #HTTP REQUESTS
  http:

  #ADD CANCELLABLE ACTIONS TO ASYNC
  async:

  #FULL TEXT SEARCH
  algolia:

  #FIRESTORE DATABASE
  firebase_core:
  cloud_firestore:
  firebase_auth:
  firebase_storage:
  firebase_messaging:
  cloud_functions:
  firebase_dynamic_links:

  #STREAM & VIDEO
  agora_rtc_engine:

  #PHONE UTILITIES
  url_launcher:
  share:
  permission_handler:
  app_settings:
  shared_preferences:
  wakelock:

  #IMAGES
  cached_network_image:
  image_cropper:
  image_picker:
  flutter_image_compress:
  carousel_pro:

  #LOCATION
  location:
  geocoder:
  flutter_google_places:
  flutter_google_places_api:
  google_maps_webservice:
  maps_launcher: ^1.2.2+2
  #flutter_background_geolocation: ^1.3.2

  #DATE & TIME
  flutter_calendar_carousel:
  add_2_calendar:

  #UI
  font_awesome_flutter:
  shimmer:

  #FINANCE
  flutter_credit_card:
  flutter_inapp_purchase:
  stripe_sdk:

  #OTHER
  flutter_typeahead:
  introduction_screen:
  flutter_masked_text:
  syncfusion_flutter_sliders:
  syncfusion_flutter_charts:
  intl_phone_field:
  liquid_pull_to_refresh:

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner:
  auto_route_generator:
  injectable_generator:
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Helvetica Neue
      fonts:
        - asset: assets/fonts/HelveticaNeueThin.ttf
          weight: 300
        - asset: assets/fonts/HelveticaNeueLight.ttf
          weight: 400
        - asset: assets/fonts/HelveticaNeue.ttf
          weight: 500
        - asset: assets/fonts/HelveticaNeueMedium.ttf
          weight: 600
        - asset: assets/fonts/HelveticaNeueBold.ttf
          weight: 700