name: webblen
description: Official Webblen App
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  #Firestore Dependencies
  cloud_firestore: ^0.14.3
  firebase_storage: ^5.0.1
  firebase_auth: ^0.18.3
  firebase_messaging: ^7.0.3
  firebase_dynamic_links: ^0.6.2
  cloud_functions: ^0.7.0+1
  flutter_native_admob: ^2.1.0+3

  #Analytics
  firebase_analytics: ^6.0.2
  facebook_app_events: ^0.7.1

  #Payment Dependencies
  flutter_credit_card: 0.1.1
  flutter_inapp_purchase: ^2.2.0
  stripe_sdk: ^2.4.2
  flutter_appauth: ^0.6.0

  #Social Dependencies
  google_sign_in: ^4.0.11
  flutter_facebook_auth: ^0.3.2
  apple_sign_in: ^0.1.0

  #Location Dependencies
  location: ^3.0.2
  location_permissions: ^3.0.0
  geoflutterfire: ^2.2.1
  geocoder: ^0.2.1
  #flutter_background_geolocation: ^1.3.2
  flutter_google_places: ^0.2.6
  google_maps_webservice: ^0.0.15

  #Image Dependencies
  cached_network_image: ^2.0.0-rc
  image_cropper: ^1.1.0
  image_picker: ^0.6.7+11
  flutter_image_compress: ^0.7.0

  #Video Dependencies
  agora_rtc_engine: ^3.1.4-rc.0
  flick_video_player: ^0.1.1
  video_compress: "2.0.0"

  #QR READ/RENDER
  qr_flutter: ^3.1.0
  qr_code_scanner:
    git:
      url: git://github.com/juliuscanute/qr_code_scanner.git

  #Phone Util Dependencies
  flutter_local_notifications: ^0.8.4
  url_launcher: ^5.4.1
  share: ^0.6.1+1
  flutter_sms: ^1.0.1
  connectivity: ^0.4.4

  #Date Time Dependencies
  timezone: ^0.5.6
  flutter_calendar_carousel: ^1.4.12

  #Other Dependencies
  rflutter_alert: ^1.0.3
  provider: ^4.1.3
  algolia: ^0.1.7
  font_awesome_flutter: 8.5.0
  liquid_pull_to_refresh: ^1.1.1
  shimmer: ^1.0.1
  flutter_masked_text: ^0.8.0
  intl: ^0.16.0
  random_string: ^1.1.0
  wakelock: ^0.1.4+2
  permission_handler: ^5.0.1+1
  introduction_screen: ^1.0.9
  adaptive_dialog: ^0.9.0
  flutter_typeahead: ^1.8.8
  carousel_pro: ^1.0.0
  particles_flutter: "^0.1.1"

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Helvetica Neue
      fonts:
        - asset: assets/fonts/HelveticaNeueThin.ttf
          weight: 300
        - asset: assets/fonts/HelveticaNeueLight.ttf
          weight: 400
        - asset: assets/fonts/HelveticaNeue.ttf
          weight: 500
        - asset: assets/fonts/HelveticaNeueMedium.ttf
          weight: 600
        - asset: assets/fonts/HelveticaNeueBold.ttf
          weight: 700