name: webblen
description: Official Webblen Application

version: 8.0.0

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  #Firestore Dependencies
  cloud_firestore: ^0.12.10
  firebase_storage: ^3.0.8
  firebase_auth: ^0.14.0+8
  firebase_messaging: ^5.1.8
  #firebase_dynamic_links: ^0.4.0
  cloud_functions: ^0.4.1+4

  #Social Dependencies
  google_sign_in: ^4.0.11
  flutter_facebook_login: ^3.0.0
#  flutter_twitter_login:
#      git: https://github.com/eudangeld/flutter_twitter_login.git

  #Location Dependencies
  location: ^2.3.5
  location_permissions: ^2.0.3
  geoflutterfire: ^2.0.3+5
  geocoder: ^0.2.1
#  flutter_background_geolocation: ^1.3.2
  flutter_google_places:
      git: https://github.com/mukai154/flutter_google_places.git
  google_maps_webservice: ^0.0.15

  #Image Dependencies
  cached_network_image: ^2.0.0-rc
  image_cropper: ^1.1.0
  image_picker: ^0.6.1+11
  flutter_image_compress: ^0.6.3
  
  #Video Dependencies
  youtube_player_flutter: ^6.0.3+2

  #QR READ/RENDER
  qr_flutter: ^3.1.0
  qr_code_scanner: ^0.0.12

  #Phone Util Dependencies
  flutter_local_notifications: ^0.8.4
  url_launcher: ^5.1.2
  contact_picker: ^0.0.2
  share: ^0.6.1+1
  flutter_sms: ^1.0.1
  connectivity: ^0.4.4

  #Date Time Dependencies
  flutter_picker: ^1.0.15
  flutter_native_timezone: ^1.0.4
  table_calendar: ^2.2.1

  #Other Dependencies
  algolia: ^0.1.7
  font_awesome_flutter: 8.5.0
  flutter_tags: ^0.4.3
  carousel_slider: ^1.3.1
  liquid_pull_to_refresh: ^1.1.1
  shimmer: ^1.0.1
  hidden_drawer_menu:  ^1.1.2
  flutter_masked_text: ^0.8.0
  flushbar: 1.8.0
  animated_text_kit: ^1.3.1
  intl: ^0.16.0
  percent_indicator: ^2.1.1+1
  random_string: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
      - family: Helvetica Neue
        fonts:
          - asset: assets/fonts/HelveticaNeueThin.ttf
            weight: 300
          - asset: assets/fonts/HelveticaNeueLight.ttf
            weight: 400
          - asset: assets/fonts/HelveticaNeue.ttf
            weight: 500
          - asset: assets/fonts/HelveticaNeueMedium.ttf
            weight: 600
          - asset: assets/fonts/HelveticaNeueBold.ttf
            weight: 700
