name: webblen
description: Official Webblen App
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  #ARCHITECTURE
  stacked:
  stacked_services:
  stacked_themes:
  get_it:
  injectable:
  auto_route:

  #HTTP REQUESTS
  http: ^0.12.2

  #ADD CANCELLABLE ACTIONS TO ASYNC
  async: ^2.4.2

  #FIRESTORE DATABASE
  firebase_core: ^0.5.0+1
  cloud_firestore: ^0.14.3+1
  firebase_auth: ^0.18.3+1
  firebase_storage: ^5.1.0
  firebase_messaging: ^7.0.3

  #PHONE UTILITIES
  url_launcher: ^5.4.1
  share: ^0.6.1+1
  permission_handler: ^5.0.1+1

  #IMAGES
  cached_network_image: ^2.0.0-rc
  image_cropper: ^1.1.0
  image_picker: ^0.6.7+11
  flutter_image_compress: ^0.7.0
  carousel_pro: ^1.0.0

  #UI
  font_awesome_flutter: 8.5.0
  shimmer: ^1.0.1
  adaptive_dialog: ^0.9.3

  #OTHER
  algolia: ^0.1.7
  flutter_typeahead: ^1.8.8
  introduction_screen: ^1.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner:
  auto_route_generator:
  injectable_generator:
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Helvetica Neue
      fonts:
        - asset: assets/fonts/HelveticaNeueThin.ttf
          weight: 300
        - asset: assets/fonts/HelveticaNeueLight.ttf
          weight: 400
        - asset: assets/fonts/HelveticaNeue.ttf
          weight: 500
        - asset: assets/fonts/HelveticaNeueMedium.ttf
          weight: 600
        - asset: assets/fonts/HelveticaNeueBold.ttf
          weight: 700