enum BottomSheetType {
  destructiveConfirmation,
  homeFilter,
  imagePicker,
  postPublished,
  postAuthorOptions,
  postOptions,
  streamPublished,
  streamCreatorOptions,
  streamOptions,
  eventPublished,
  eventCreatorOptions,
  eventOptions,
  currentUserOptions,
  userOptions,
}
