enum BottomSheetType {
  addContent,
  newContentConfirmation,
  addContentSuccessful,
  contentOptions,
  contentAuthorOptions,
  destructiveConfirmation,
  homeFilter,
  imagePicker,
  currentUserOptions,
  userOptions,
  calendar,
  displayContentGifters,
  giftWBLN,
  purchaseWBLN,
}
