class Strings {
  static final String googleAPIKEY = "AIzaSyApD1l8k7XAUQ7jOMA0p9edI6JllSbCawM";
  static final String twitterCONSUMERKEY = "qE3eqc6zEr1iFamNEkyyJzztT";
  static final String twitterCONSUMERSECRET = "8nKtKawnraVuhYJVE0yAha153qeG01KgkiA0uw6HjbXIzIk5wm";
  static final String ethNetworkID = "c873a87ae50a4095ae3e3af99e42016f";
  static final String ethNetworkSecret = "1a2ba470d48d46cf9840cca6cbe38baa";
  static final String stripePublishableKey = "pk_test_gYHQOvqAIkPEMVGQRehk3nj4009Kfodta1";
  static final String stripeSecretKey = "sk_test_HwrGAbGCJajUhp8uawtc3QSi00dXPaPcCu";
  static final String stripeTestClientID = "ca_Gb0FkpBEdu1zmDMxUfBanAeuRqFCtjuR";
  static final List<String> statesList = [
    'AL',
    'AK',
    'AS',
    'AZ',
    'AR',
    'CA',
    'CO',
    'CT',
    'DE',
    'DC',
    'FM',
    'FL',
    'GA',
    'GU',
    'HI',
    'ID',
    'IL',
    'IN',
    'IA',
    'KS',
    'KY',
    'LA',
    'ME',
    'MH',
    'MD',
    'MA',
    'MI',
    'MN',
    'MS',
    'MO',
    'MT',
    'NE',
    'NV',
    'NH',
    'NJ',
    'NM',
    'NY',
    'NC',
    'ND',
    'MP',
    'OH',
    'OK',
    'OR',
    'PW',
    'PA',
    'PR',
    'RI',
    'SC',
    'SD',
    'TN',
    'TX',
    'UT',
    'VT',
    'VI',
    'VA',
    'WA',
    'WV',
    'WI',
    'WY'
  ];
}
